./n.sh data/景,paisaje.yml
./n.sh data/映,reflejar.yml
./n.sh data/明,brillante.yml
./n.sh data/昌,próspero.yml
./n.sh data/早,temprano.yml
./n.sh data/旨,delicioso.yml
./n.sh data/旦,amanecer.yml
./n.sh data/既,previamente.yml
./n.sh data/方,Direccion.yml
./n.sh data/新,nuevo.yml
./n.sh data/文,oración.yml
./n.sh data/数,número.yml
./n.sh data/教,enseñar.yml
./n.sh data/放,Liberar.yml
./n.sh data/改,Reformar.yml
./n.sh data/支,rama.yml
./n.sh data/撮,TomarFotos.yml
./n.sh data/撃,azotar.yml
./n.sh data/揺,mecerse.yml
./n.sh data/接,tocar.yml
./n.sh data/採,recolectar.yml
./n.sh data/掌,manipular.yml
./n.sh data/授,impartir.yml
./n.sh data/捕,capturar.yml
./n.sh data/挨,acercamiento.yml
./n.sh data/持,Sostener.yml
./n.sh data/拶,inminente.yml
./n.sh data/拝,venerar.yml
./n.sh data/拒,repeler.yml
./n.sh data/披,Exponer.yml
./n.sh data/投,lanzar.yml
./n.sh data/技,pericia.yml
./n.sh data/払,pagar.yml
./n.sh data/才,años_de_edad.yml
./n.sh data/手,mano.yml
./n.sh data/或,ciertos.yml
./n.sh data/感,emoción.yml
./n.sh data/愛,amor.yml
./n.sh data/意,idea.yml
./n.sh data/情,sentimientos.yml
./n.sh data/息,respiración.yml
./n.sh data/恥,Vergüenza.yml
./n.sh data/恋,amor.yml
./n.sh data/急,apresurarse.yml
./n.sh data/思,pensar.yml
./n.sh data/応,adaptar.yml
./n.sh data/志,resolución.yml
./n.sh data/待,Esperar.yml
./n.sh data/彼,él.yml
./n.sh data/当,acertar.yml
./n.sh data/引,tirar.yml
./n.sh data/廿,veinte.yml
./n.sh data/廷,Tribunal.yml
./n.sh data/度,grado.yml
./n.sh data/店,tienda.yml
./n.sh data/幾,cuántos.yml
./n.sh data/年,año.yml
./n.sh data/干,secar.yml
./n.sh data/常,Normal.yml
./n.sh data/帰,Regresar.yml
./n.sh data/師,experto.yml
./n.sh data/市,mercado.yml
./n.sh data/巻,pergamino.yml
./n.sh data/己,El_yo.yml
./n.sh data/差,distinción.yml
./n.sh data/左,izquierda.yml
./n.sh data/嵐,tormenta.yml
./n.sh data/島,isla.yml
./n.sh data/山,montaña.yml
./n.sh data/属,genus.yml
./n.sh data/尻,trasero.yml
./n.sh data/少,poco.yml
./n.sh data/小,pequeño.yml
./n.sh data/導,guiar.yml
./n.sh data/将,líder.yml
./n.sh data/専,especialidad.yml
./n.sh data/寺,templo_budista.yml
./n.sh data/寸,medida.yml
./n.sh data/寧,más_bien.yml
./n.sh data/寂,soledad.yml
./n.sh data/宿,hostal.yml
./n.sh data/家,casa.yml
./n.sh data/客,invitado.yml
./n.sh data/定,determinación.yml
./n.sh data/安,relajo.yml
./n.sh data/学,estudiar.yml
./n.sh data/孝,devoción_filial.yml
./n.sh data/字,letra.yml
./n.sh data/子,niño.yml
./n.sh data/婆,Abuelita.yml
./n.sh data/委,comité.yml
./n.sh data/始,principio.yml
./n.sh data/姉,hermana_mayor.yml
./n.sh data/妹,hermana_menor.yml
./n.sh data/妥,amable.yml
./n.sh data/妊,Embarazada.yml
./n.sh data/妃,Reina.yml
./n.sh data/好,gustar.yml
./n.sh data/女,mujer.yml
./n.sh data/奨,exhortar.yml
./n.sh data/央,centro.yml
./n.sh data/太,gordo.yml
./n.sh data/大,grande.yml
./n.sh data/多,muchos.yml
./n.sh data/外,exterior.yml
./n.sh data/夕,noche.yml
./n.sh data/売,Vender.yml
./n.sh data/士,guerrero.yml
./n.sh data/増,Aumento.yml
./n.sh data/堅,estricto.yml
./n.sh data/堂,SalaPública.yml
./n.sh data/培,cultivar.yml
./n.sh data/預,depósito.yml
./n.sh data/項,parrafo.yml
./n.sh data/頃,tiempos.yml
./n.sh data/頁,pagina.yml
./n.sh data/音,Sonido.yml
./n.sh data/電,Electricidad.yml
./n.sh data/雪,Nieve.yml
./n.sh data/難,difícil.yml
./n.sh data/際,ocasión.yml
./n.sh data/隅,esquina.yml
./n.sh data/険,escarpado.yml
./n.sh data/間,intervalo.yml
./n.sh data/門,puertas_de_ciudad.yml
./n.sh data/鋭,Afilado.yml
./n.sh data/釜,Olla.yml
./n.sh data/金,oro.yml
./n.sh data/量,cantidad.yml
./n.sh data/里,ri.yml
./n.sh data/酢,vinagre.yml
./n.sh data/週,Semana.yml
./n.sh data/速,rápido.yml
./n.sh data/逐,Cumplir.yml
./n.sh data/返,devolver.yml
./n.sh data/近,cerca.yml
./n.sh data/辛,picante.yml
./n.sh data/輸,transportar.yml
./n.sh data/軟,blando.yml
./n.sh data/車,coche.yml
./n.sh data/跡,rastro.yml
./n.sh data/足,pie.yml
./n.sh data/走,correr.yml
./n.sh data/赤,rojo.yml
./n.sh data/贈,regalo.yml
./n.sh data/贈,Regalar.yml
./n.sh data/賠,compensación.yml
./n.sh data/賞,Premio.yml
./n.sh data/資,bienes.yml
./n.sh data/賀,felicitaciones.yml
./n.sh data/買,comprar.yml
./n.sh data/販,márketing.yml
./n.sh data/貝,almeja.yml
./n.sh data/豚,Cerdo.yml
./n.sh data/豆,haba.yml
./n.sh data/谷,valle.yml
./n.sh data/諮,consultar.yml
./n.sh data/読,leer.yml
./n.sh data/説,Rumor.yml
./n.sh data/誤,error.yml
./n.sh data/語,idioma.yml
./n.sh data/話,hablar.yml
./n.sh data/許,permitir.yml
./n.sh data/設,escena.yml
./n.sh data/訪,Visitar.yml
./n.sh data/記,Escriba.yml
./n.sh data/計,proyecto.yml
./n.sh data/言,decir.yml
./n.sh data/覚,memorizar.yml
./n.sh data/規,estándar.yml
./n.sh data/見,ver.yml
./n.sh data/西,oeste.yml
./n.sh data/裳,Falda.yml
./n.sh data/裕,abundante.yml
./n.sh data/裂,Ruptura.yml
./n.sh data/被,Incurrir.yml
./n.sh data/表,superficie.yml
./n.sh data/行,Ir.yml
./n.sh data/蝶,Mariposa.yml
./n.sh data/蛙,rana.yml
./n.sh data/蛍,luciérnaga.yml
./n.sh data/蛇,serpiente.yml
./n.sh data/蚕,GusanoSeda.yml
./n.sh data/虹,Arcoiris.yml
./n.sh data/虫,insecto.yml
./n.sh data/薬,medicina.yml
./n.sh data/薄,desteñido.yml
./n.sh data/蕎,alforfón.yml
./n.sh data/葬,Funeral.yml
./n.sh data/葉,hoja.yml
./n.sh data/菜,verdura.yml
./n.sh data/菊,crisantemo.yml
./n.sh data/茶,té.yml
./n.sh data/良,Bueno.yml
./n.sh data/艮,Plata.yml
./n.sh data/舌,lengua.yml
./n.sh data/自,uno_mismo.yml
./n.sh data/脱,Desnudarse.yml
./n.sh data/脈,venas.yml
./n.sh data/脇,axila.yml
./n.sh data/脅,amenaza.yml
./n.sh data/胞,Placenta.yml
./n.sh data/背,estatura.yml
./n.sh data/胃,estómago.yml
./n.sh data/肪,Obeso.yml
./n.sh data/肢,extremidad.yml
./n.sh data/聞,Oir.yml
./n.sh data/耳,Oreja.yml
./n.sh data/老,anciano.yml
./n.sh data/習,aprender.yml
./n.sh data/羽,plumas.yml
./n.sh data/羨,envidia.yml
./n.sh data/羊,oveja.yml
./n.sh data/置,colocar.yml
./n.sh data/結,atar.yml
./n.sh data/細,delgado.yml
./n.sh data/紅,carmín.yml
./n.sh data/紀,crónica.yml
./n.sh data/糸,hilo.yml
./n.sh data/粗,chapuza.yml
./n.sh data/粋,chic.yml
./n.sh data/粉,harina.yml
./n.sh data/米,arroz.yml
./n.sh data/簡,sencillo.yml
./n.sh data/箱,caja.yml
./n.sh data/筒,cilindro.yml
./n.sh data/筋,músculo.yml
./n.sh data/笹,bambú_enano.yml
./n.sh data/笠,sombrero_bambú.yml
./n.sh data/笑,risa.yml
./n.sh data/竹,bambú.yml
./n.sh data/竜,Dragón.yml
./n.sh data/立,de_pie.yml
./n.sh data/空,Vacío.yml
./n.sh data/移,trasladar.yml
./n.sh data/秋,otoño.yml
./n.sh data/私,yo.yml
./n.sh data/祭,festividad.yml
./n.sh data/票,voto.yml
./n.sh data/破,Desgarrar.yml
./n.sh data/砲,Cañón.yml
./n.sh data/石,piedra.yml
./n.sh data/瞬,Pestañeo.yml
./n.sh data/督,entrenador.yml
./n.sh data/着,vestir.yml
./n.sh data/真,verdad.yml
./n.sh data/直,directamente.yml
./n.sh data/目,ojo.yml
./n.sh data/皮,Pellejo.yml
./n.sh data/皇,emperador.yml
./n.sh data/皆,todos.yml
./n.sh data/百,cien.yml
./n.sh data/白,blanco.yml
./n.sh data/疑,duda.yml
./n.sh data/町,ciudad.yml
./n.sh data/男,hombre.yml
./n.sh data/由,por_lo_que.yml
./n.sh data/田,campo_de_arroz.yml
./n.sh data/産,producción.yml
./n.sh data/生,vida.yml
./n.sh data/理,Logica.yml
./n.sh data/球,balón.yml
./n.sh data/現,presente.yml
./n.sh data/王,rey.yml
./n.sh data/玉,joya.yml
./n.sh data/猫,gato.yml
./n.sh data/独,solitario.yml
./n.sh data/犬,perro.yml
./n.sh data/特,especial.yml
./n.sh data/物,Cosa.yml
./n.sh data/牛,vaca.yml
./n.sh data/爪,garras.yml
./n.sh data/焼,freír.yml
./n.sh data/無,nada.yml
./n.sh data/烈,Ardiente.yml
./n.sh data/炊,cocinar.yml
./n.sh data/灯,lámpara.yml
./n.sh data/火,fuego.yml
./n.sh data/激,Violento.yml
./n.sh data/漆,laca.yml
./n.sh data/漁,pescar.yml
./n.sh data/滝,Catarata.yml
./n.sh data/満,lleno.yml
./n.sh data/湯,agua_caliente.yml
./n.sh data/飾,decorar.yml
./n.sh data/飲,Beber.yml
./n.sh data/食,Comer.yml
./n.sh data/風,viento.yml
./n.sh data/類,tipo_de.yml
./n.sh data/頭,mollera.yml
./n.sh data/載,Cargar.yml
./n.sh data/賊,Bandido.yml
./n.sh data/誠,sincero.yml
./n.sh data/試,Examen.yml
./n.sh data/茂,Exuberante.yml
./n.sh data/胆,vesícula_biliar.yml
./n.sh data/滅,Destruir.yml
./n.sh data/減,Menguar.yml
./n.sh data/栽,Plantío.yml
./n.sh data/早,amanecer.yml
./n.sh data/旦,alba.yml
./n.sh data/成,Convertirse.yml
./n.sh data/式,Estilo.yml
./n.sh data/威,Intimidar.yml
./n.sh data/域,Zona.yml
./n.sh data/城,Castillo.yml
./n.sh data/唱,canto.yml
./n.sh data/呂,espina_dorsal.yml
./n.sh data/吾,el_yo_metafísico.yml
./n.sh data/時,tiempo.yml
./n.sh data/天,cielo.yml
./n.sh data/月,luna.yml
./n.sh data/川,rio.yml
./n.sh data/心,corazón.yml
./n.sh data/救,salvación.yml
./n.sh data/雨,lluvia.yml
./n.sh data/首,cuello.yml
./n.sh data/美,belleza.yml
./n.sh data/築,fabricar.yml
./n.sh data/算,calcular.yml
./n.sh data/策,estratagema.yml
./n.sh data/答,solución.yml
./n.sh data/等,etcétera.yml
./n.sh data/佐,asistente.yml
./n.sh data/住,habitar.yml
./n.sh data/位,rango.yml
./n.sh data/但,sin_embargo.yml
./n.sh data/訓,instrucciones.yml
./n.sh data/相,inter.yml
./n.sh data/烏,cuervo.yml
./n.sh data/悠,remoto.yml
./n.sh data/個,individual.yml
./n.sh data/信,fe.yml
./n.sh data/依,confiar.yml
./n.sh data/侍,camarero.yml
./n.sh data/例,ejemplo.yml
./n.sh data/佳,excelente.yml
./n.sh data/伯,conde.yml
./n.sh data/伏,postrar.yml
./n.sh data/件,caso.yml
./n.sh data/他,otro.yml
./n.sh data/仕,atender.yml
./n.sh data/仏,Buda.yml
./n.sh data/仁,humanitario.yml
./n.sh data/亭,pabellón.yml
./n.sh data/高,recibir.yml
./n.sh data/高,alto.yml
./n.sh data/貞,recto.yml
./n.sh data/致,facer.yml
./n.sh data/至,clímax.yml
./n.sh data/義,virtud.yml
./n.sh data/競,disputa.yml
./n.sh data/童,juvenil.yml
./n.sh data/瞳,pupila.yml
./n.sh data/熟,madurar.yml
./n.sh data/涼,refrescante.yml
./n.sh data/橋,puente.yml
./n.sh data/我,ego.yml
./n.sh data/帝,soberano.yml
./n.sh data/室,sala.yml
./n.sh data/嬌,atractiva.yml
./n.sh data/塾,academia_de_repaso.yml
./n.sh data/到,llegar.yml
./n.sh data/億,cien_millones.yml
./n.sh data/儀,ceremonia.yml
./n.sh data/催,anfitrión.yml
./n.sh data/偵,espiar.yml
./n.sh data/停,parada.yml
./n.sh data/倣,emular.yml
./n.sh data/倒,derrocamiento.yml
./n.sh data/驚,sorprender.yml
./n.sh data/長,largo.yml
./n.sh data/警,amonestar.yml
./n.sh data/褒,halagar.yml
./n.sh data/知,saber.yml
./n.sh data/痴,estúpido.yml
./n.sh data/痢,diarrea.yml
./n.sh data/痘,viruela.yml
./n.sh data/痒,comezón.yml
./n.sh data/症,síntoma.yml
./n.sh data/疫,epidemia.yml
./n.sh data/畝,surco.yml
./n.sh data/強,fuerte.yml
./n.sh data/弱,débil.yml
./n.sh data/弘,extenso.yml
./n.sh data/弔,pésame.yml
./n.sh data/弓,arco.yml
./n.sh data/吏,funcionario.yml
./n.sh data/史,historia.yml
./n.sh data/匿,esconderse.yml
./n.sh data/区,distrito.yml
./n.sh data/匹,igual.yml
./n.sh data/匠,artesano.yml
./n.sh data/傷,herida.yml
./n.sh data/保,conservar.yml
./n.sh data/侮,mofarse_de.yml
./n.sh data/使,usar.yml
./n.sh data/弟,hermano_pequeño.yml
./n.sh data/巧,habilidad.yml
./n.sh data/号,apodo.yml
./n.sh data/費,gasto.yml
./n.sh data/汚,sucio.yml
./n.sh data/口,boca.yml
./n.sh data/砂,arena.yml
./n.sh data/晶,destello.yml
./n.sh data/蚊,mosquito.yml
./n.sh data/姦,ruidoso.yml
./n.sh data/明,claro.yaml
./n.sh data/苗,sembrar.yml
./n.sh data/父,padre.yml
./n.sh data/昌,prospero.yml
./n.sh data/componentes
./n.sh data/日,sol.yml
./n.sh data/エ,tecnica.yml
./n.sh data/一,uno.yml
./n.sh data/丁,calle.yml
./n.sh data/万,diez_mil.yml
./n.sh data/七,siete.yml
./n.sh data/三,tres.yml
./n.sh data/不,negativo.yml
./n.sh data/与,conceder.yml
./n.sh data/世,generación.yml
./n.sh data/両,ambos.yml
./n.sh data/中,en_medio_de.yml
./n.sh data/丸,redondo.yml
./n.sh data/久,duradero.yml
./n.sh data/九,nueve.yml
./n.sh data/乳,leche.yml
./n.sh data/亀,tortuga.yml
./n.sh data/予,de_antemano.yml
./n.sh data/五,cinco.yml
./n.sh data/亘,atravesar.yml
./n.sh data/京,capital.yml
./n.sh data/仙,ermitaño.yml
./n.sh data/代,sustituto.yml
./n.sh data/令,órdenes.yml
./n.sh data/休,descansar.yml
./n.sh data/人,persona.yml
./n.sh data/交,contraste.yml
./n.sh data/争,contienda.yml
./n.sh data/乙,entrañas_pescado.yml
./n.sh data/主,amo.yml
./n.sh data/下,debajo_de.yml
./n.sh data/上,encima_de.yml
./n.sh data/仮,provisional.yml
./n.sh data/二,dos.yml
./n.sh data/仲,intermediario.yml
./n.sh data/馬,equino.yml
./n.sh data/𠂢,ramificar.yml
./n.sh data/鯨,ballena.yml
./n.sh data/黒,negro.yml
./n.sh data/麦,cebada.yml
./n.sh data/鼻,nariz.yml
./n.sh data/鯉,carpa.yml
./n.sh data/鮮,fresco.yml
./n.sh data/魚,pescado.yml
./n.sh data/鳥,pájaro.yml
./n.sh data/鮫,tiburón.yml
./n.sh data/駐,aparcar.yml
./n.sh data/穴,agujero.yml
./n.sh data/坂,pendiente.yml
./n.sh data/地,Terreno.yml
./n.sh data/圭,joya_cuadrada.yml
./n.sh data/土,tierra.yml
./n.sh data/国,país.yml
./n.sh data/四,cuatro.yml
./n.sh data/品,mercancías.yml
./n.sh data/哀,patético.yml
./n.sh data/和,armonía.yml
./n.sh data/呉,dar.yml
./n.sh data/吾,yo_interior.yml
./n.sh data/吐,escupir.yml
./n.sh data/名,nombre.yml
./n.sh data/吊,ahorcar.yml
./n.sh data/吉,buena_fortuna.yml
./n.sh data/合,encajar.yml
./n.sh data/各,cada_uno.yml
./n.sh data/右,derecha.yml
./n.sh data/台,pedestal.yml
./n.sh data/可,posible.yml
./n.sh data/古,viejo.yml
./n.sh data/受,aceptar.yml
./n.sh data/取,Tomar.yml
./n.sh data/叔,tío.yml
./n.sh data/反,anti.yml
./n.sh data/参,presenciar.yml
./n.sh data/厚,grueso.yml
./n.sh data/厘,rin.yml
./n.sh data/博,Dr..yml
./n.sh data/単,simple.yml
./n.sh data/半,mitad.yml
./n.sh data/午,caballo.yml
./n.sh data/千,mil.yml
./n.sh data/十,diez.yml
./n.sh data/医,médico.yml
./n.sh data/北,norte.yml
./n.sh data/温,caliente.yml
./n.sh data/淑,grácil.yml
./n.sh data/海,mar.yml
./n.sh data/浴,bañarse.yml
./n.sh data/浮,flotar.yml
./n.sh data/活,animado.yml
./n.sh data/津,ensenada.yml
./n.sh data/洗,lavar.yml
./n.sh data/洋,océano.yml
./n.sh data/泳,natacion.yml
./n.sh data/泣,llorar.yml
./n.sh data/波,Ola.yml
./n.sh data/泡,burbuja.yml
./n.sh data/化,cambio.yml
./n.sh data/包,envolver.yml
./n.sh data/勿,no.yml
./n.sh data/勧,persuadir.yml
./n.sh data/勢,tropas.yml
./n.sh data/募,reclutar.yml
./n.sh data/労,fatiga.yml
./n.sh data/励,animar.yml
./n.sh data/努,esfuerzo.yml
./n.sh data/劣,inferioridad.yml
./n.sh data/加,añadir.yml
./n.sh data/加,agregar.yml
./n.sh data/功,éxito.yml
./n.sh data/力,fuerza.yml
./n.sh data/副,vice_.yml
./n.sh data/剖,dividir.yml
./n.sh data/判,sentencia.yml
./n.sh data/列,Hilera.yml
./n.sh data/分,parte.yml
./n.sh data/刃,filo.yml
./n.sh data/刀,espada.yml
./n.sh data/凍,Helado.yml
./n.sh data/冷,enfriar.yml
./n.sh data/写,copiar.yml
./n.sh data/冒,riesgo.yml
./n.sh data/再,de_nuevo.yml
./n.sh data/円,circulo.yml
./n.sh data/六,seis.yml
./n.sh data/八,ocho.yml
./n.sh data/先,delante.yml
./n.sh data/兄,hermano_mayor.yml
./n.sh data/修,disciplina.yml
./n.sh data/余,excesivo.yml
./n.sh data/何,que.yml
./n.sh data/体,cuerpo.yml
./n.sh data/.gitkeep
./n.sh data/油,aceite.yml
./n.sh data/沸,hervir.yml
./n.sh data/河,Gran_río.yml
./n.sh data/沫,salpicar.yml
./n.sh data/没,ahogarse.yml
./n.sh data/沖,altamar.yml
./n.sh data/決,decisión.yml
./n.sh data/池,Estanque.yml
./n.sh data/江,riachuelo.yml
./n.sh data/汗,sudor.yml
./n.sh data/求,solicitud.yml
./n.sh data/永,eternidad.yml
./n.sh data/氷,hielo.yml
./n.sh data/水,agua.yml
./n.sh data/比,comparar.yml
./n.sh data/毎,todos_los.yml
./n.sh data/母,madre.yml
./n.sh data/殻,cáscara.yml
./n.sh data/残,ElResto.yml
./n.sh data/殉,Martirio.yml
./n.sh data/死,Muerte.yml
./n.sh data/歩,andar.yml
./n.sh data/正,Correcto.yml
./n.sh data/止,detener.yml
./n.sh data/歌,canción.yml
./n.sh data/欠,Ausencia.yml
./n.sh data/標,señal.yml
./n.sh data/様,sama,don.yml
./n.sh data/構,postura.yml
./n.sh data/楼,atalaya.yml
./n.sh data/森,bosque.yml
./n.sh data/棟,Caballete.yml
./n.sh data/案,plan.yml
./n.sh data/校,escuela.yml
./n.sh data/架,erigir.yml
./n.sh data/枝,leño.yml
./n.sh data/林,arboleda.yml
./n.sh data/板,tabla.yml
./n.sh data/東,este.yml
./n.sh data/杯,taza_de.yml
./n.sh data/来,venir.yml
./n.sh data/束,manojo.yml
./n.sh data/机,escritorio.yml
./n.sh data/本,libro.yml
./n.sh data/末,extremo.yml
./n.sh data/未,todavia.yml
./n.sh data/木,árbol.yml
./n.sh data/朋,compañero.yml
./n.sh data/有,posesión.yml
./n.sh data/最,Máximo.yml
./n.sh data/曽,Anteriormente.yml
./n.sh data/書,escribir.yml
./n.sh data/曜,dia_de_la_semana.yml
./n.sh data/暗,oscuro.yml
./n.sh data/暖,templado.yml
./n.sh data/党,PartidoPolitico.yml
